tinyMCE.addI18n('pt_br.advanced',{
style_select:"Estilo",
font_size:"Tamanho(Fonte)",
fontdefault:"Familia(Fonte)",
block:"Formato",
paragraph:"Paragrafo",
div:"Div",
address:"Endereço",
pre:"Pré-formatado",
h1:"Heading 1",
h2:"Heading 2",
h3:"Heading 3",
h4:"Heading 4",
h5:"Heading 5",
h6:"Heading 6",
blockquote:"Blockquote",
code:"Code",
samp:"Código de exemplo",
dt:"Definição de termo ",
dd:"descrição da Definição",
bold_desc:"Negrito (Ctrl+B)",
italic_desc:"Itálico (Ctrl+I)",
underline_desc:"Sublinhar (Ctrl+U)",
striketrough_desc:"Tachado",
justifyleft_desc:"Alinhar à esquerda",
justifycenter_desc:"Alinhar ao centro",
justifyright_desc:"Alinhar à direita",
justifyfull_desc:"Alinha Geral",
bullist_desc:"Lista desordenada",
numlist_desc:"Lista Ordenada",
outdent_desc:"Outdent",
indent_desc:"Travessão",
undo_desc:"Desfazer (Ctrl+Z)",
redo_desc:"Refazer (Ctrl+Y)",
link_desc:"Inserir/editar link",
unlink_desc:"Unlink",
image_desc:"Inserir/editar imagem",
cleanup_desc:"Limpar código confuso",
code_desc:"Editar código fonte HTML",
sub_desc:"Subscrito",
sup_desc:"Sobrescrito",
hr_desc:"Inserir régua horizontal",
removeformat_desc:"Remover formatação",
custom1_desc:"Sua descrição personalizada aqui",
forecolor_desc:"Selecionar cor texto",
backcolor_desc:"Selecionar cor de fundo",
charmap_desc:"Inserir caráter personalizado",
visualaid_desc:"Alternar orientações/elementos invisíveis",
anchor_desc:"Inserir/editar âncora",
cut_desc:"Cortar",
copy_desc:"Copiar",
paste_desc:"Colar",
image_props_desc:"Propriedades da Imagem",
newdocument_desc:"Novo documento",
help_desc:"Ajuda",
blockquote_desc:"Bloco de texto",
clipboard_msg:"Copiar/Cortar/Colar não está disponível no Mozilla e Firefox. \n Você deseja mais informações sobre esta questão?",
path:"Caminho",
newdocument:"Tem certeza de que deseja limpar todos os conteúdos?",
toolbar_focus:"Ir para a Ferramenta de botões - Alt+Q, Ir para o editor - Alt-Z, Ir para o elemento caminho - Alt-X",
more_colors:"Mais cores"
});