tinyMCE.addI18n('pt_br.advimage_dlg',{
tab_general:"Geral",
tab_appearance:"Aparência",
tab_advanced:"Opções",
general:"Geral",
title:"Título",
preview:"Prever",
constrain_proportions:"Restringir proporções",
langdir:"Sentido do Idioma",
langcode:"Código de Idioma",
long_desc:"Descrição completa do link",
style:"Estilo",
classes:"Classes",
ltr:"Esquerda para Direita",
rtl:"Direita para Esquerda",
id:"Id",
map:"Mapa de Imagem",
swap_image:"Swap imagem",
alt_image:"Imagem Alternativa",
mouseover:"quando o mouse está sobre",
mouseout:"quando o mouse está saindo de cima",
misc:"Diversos",
example_img:"Aspecto da imagem pré-visualizada",
missing_alt:"Tem certeza que deseja continuar sem incluir a Descrição desta imagem? Sem uma descrição, a imagem pode não ser acessível a alguns usuários com deficiência, ou para aqueles que utilizam um navegador de texto, ou navegar na Internet com imagens desligadas.",
dialog_title:"Inserir/editar imagem",
src:"URL da Imagem",
alt:"Descrição da Imagem",
list:"Listar Imagem",
border:"Borda",
dimensions:"Dimensões",
vspace:"Espaço Vertical",
hspace:"Espaço Horizontal",
align:"Alinhamento",
align_baseline:"Baseline",
align_top:"Topo",
align_middle:"Meio",
align_bottom:"Final",
align_texttop:"Texto do topo",
align_textbottom:"Texto do Final",
align_left:"Esquerda",
align_right:"Direita",
image_list:"Listar Imagem"
});