tinyMCE.addI18n('pt_br.advanced_dlg',{
about_title:"Sobre o TinyMCE",
about_general:"Sobre",
about_help:"Ajuda",
about_license:"Licença",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Autor",
about_version:"Versão",
about_loaded:"plugins Carregados",
anchor_title:"Inserir/editar âncora",
anchor_name:"Nome da Âncora",
code_title:"Editor de código Fonte HTML",
code_wordwrap:"Embrulhar Palavra",
colorpicker_title:"Escolher uma côr",
colorpicker_picker_tab:"Picker",
colorpicker_picker_title:"Color picker",
colorpicker_palette_tab:"Palette",
colorpicker_palette_title:"Palette colors",
colorpicker_named_tab:"Named",
colorpicker_named_title:"Named colors",
colorpicker_color:"Côr:",
colorpicker_name:"Nome:",
charmap_title:"Selecione caracter personalizado",
image_title:"Inserir/editar imagem",
image_src:"URL da imagem",
image_alt:"descrição da Imagem",
image_list:"Imagem list",
image_border:"Borda",
image_dimensions:"Dimensões",
image_vspace:"Espaço Vertical",
image_hspace:"Espaço Horizontal",
image_align:"Alinhamento",
image_align_baseline:"Baseline",
image_align_top:"Topo",
image_align_middle:"Meio",
image_align_bottom:"Fundo",
image_align_texttop:"Texto do topo",
image_align_textbottom:"Texto no fundo",
image_align_left:"Esquerda",
image_align_right:"Direita",
link_title:"Inserir/editar link",
link_url:"Link URL",
link_target:"Alvo",
link_target_same:"Abrir link na mesma Janela",
link_target_blank:"Abrir link em uma nova Janela",
link_titlefield:"Título",
link_is_email:"O URL que você digitou parece ser um endereço de e-mail. Você quer adicionar o exigido mailto: prefixo?",
link_is_external:"O URL que você digitou parece ser um link externo, você quer adicionar o exigido http:// prefixo?",
link_list:"Listar Link"
});