tinyMCE.addI18n('pt_br.advlink_dlg',{
title:"Incluir/editar link",
url:"Link da URL",
target:"Target",
titlefield:"Título",
is_email:"O URL que você digitou parece ser um endereço de e-mail. Você quer adicionar o exigido mailto: prefixo?",
is_external:"O URL que você digitou parece ser um link externo. Você quer adicionar o exigido http:// prefixo?",
list:"Listar Link",
general_tab:"Geral",
popup_tab:"Popup",
events_tab:"Eventos",
advanced_tab:"Avançado",
general_props:"Propriedades Gerais",
popup_props:"Propiedades do Popup",
event_props:"Eventos",
advanced_props:"Propriedade Avançada",
popup_opts:"Opções",
anchor_names:"Âncoras",
target_same:"Abrir na mesma janela / frame",
target_parent:"Abrir na janela mãe / frame",
target_top:"Abrir em um frame superior (substitui todos os frames existentes)",
target_blank:"Abrir em uma nova Janela",
popup:"Popup Javascript",
popup_url:"URL do Popup",
popup_name:"Nome da Janela",
popup_return:"Incluir 'retornar falso'",
popup_scrollbars:"Mostrar scrollbars",
popup_statusbar:"Mostrar barra de status",
popup_toolbar:"Mostrar barra de ferramentas",
popup_menubar:"Mostrar barra de Menu",
popup_location:"Mostrar o local da barra",
popup_resizable:"Janela será redimensionável",
popup_dependent:"Dependente (Mozilla/Firefox somente)",
popup_size:"Tamanho",
popup_position:"Posição (X/Y)",
id:"Id",
style:"Estilo",
classes:"Classes",
target_name:"Nome do Alvo",
langdir:"Direção do Idioma",
target_langcode:"Alvo do Idioma",
langcode:"Código de Idioma",
encoding:"Alvo da codificação de caracteres",
mime:"Alvo para o tipo MIME",
rel:"Relações com a página meta",
rev:"Relações do alvo para a página",
tabindex:"Tabindex",
accesskey:"Accesskey",
ltr:"Esquerda para Direita",
rtl:"Direita para Esquerda",
link_list:"Listar Link"
});